[package]
name = "ati-adl-sys"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
int-enum = "~0.4.0"
libc = "~0.2.120"
libloading = "~0.7.2"
strum = "~0.24.0"
strum_macros = "~0.24.0"
