[package]
name = "gpu-fan-alert"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "~1.0.56"
cpal = "~0.13.5"
crossbeam-channel = "~0.5.2"
ctrlc = "~3.2.1"
int-enum = "~0.4.0"
libc = "~0.2.119"
libloading = "~0.7.2"
strum = "~0.24.0"
strum_macros = "~0.24.0"
time = { version="~0.3.7", features=["formatting", "local-offset"] }
