[package]
name = "gpu-fan-alert"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
ati_adl_sdk_sys = { path = "ati_adl_sdk_sys" }
